// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE4_2nBWxi49EDiJiIKqaOAg70MCKD-Ig',
    appId: '1:542358620373:web:3772eee418ce7c50b47a5c',
    messagingSenderId: '542358620373',
    projectId: 'labproject-10757',
    authDomain: 'labproject-10757.firebaseapp.com',
    storageBucket: 'labproject-10757.firebasestorage.app',
    measurementId: 'G-9477R2ERGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCutyXzA6I2hsXzqv4spADX3cIdVFWYkPc',
    appId: '1:542358620373:android:b399a1aad77b0b63b47a5c',
    messagingSenderId: '542358620373',
    projectId: 'labproject-10757',
    storageBucket: 'labproject-10757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRjAHYtTu0zdJTRYJB8yTS5KFyHXeyug0',
    appId: '1:542358620373:ios:eed99b57cd9853ccb47a5c',
    messagingSenderId: '542358620373',
    projectId: 'labproject-10757',
    storageBucket: 'labproject-10757.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliverySystem',
  );
}
